# Meta
title: conflores
title_alt: c✿nflores
description: >-
  Not sure what to write here yet
url: "https://conflor.es"

# Contact info
email: eri@inventati.org
github:
  username: eerii

# Blog defaults
timezone: Europe/Madrid
permalink: /blog/:slug
future: false
toc: true

# Jekyll config
theme: jekyll-bear-theme
plugins:
  - jekyll-feed

# Theme config
nav_links:
  # TODO: Write actual about page
  about: https://www.linkedin.com/in/eripazosperez
  code: https://github.com/eerii
collections:
  my_tags:
    output: true
    permalink: /tagged/:slug
defaults:
  -
    scope:
      path: ""
      type: my_tags
    values:
      layout: tagged

# Nix
exclude:
  - README.md
  - LICENSE.md
  - gemset.nix
  - flake.nix
  - flake.lock
